#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-airsonic
SERVICE_NAME="airsonic-advanced"

check_container_initialized
check_service_initialized init

URL_BASE="/${URL_PATH}"
IFS=" " read -r -a RUN_ARRAY <<< "${AIRSONIC_ARGS}"

liftoff

print_start "Starting Airsonic Advanced $(grep -o "ADD: Airsonic Advanced .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $4}')"
cd /app
exec s6-setuidgid ${AIRSONIC_USER} java \
            -Dlog4j2.formatMsgNoLookups=true \
            -Dairsonic.defaultMusicFolder=/data/music \
            -Dairsonic.defaultPlaylistFolder=/data/playlists \
            -Dairsonic.defaultPodcastFolder=/data/podcasts \
            -Dairsonic.home="${CONFIG_PATH}" \
            -Djava.awt.headless=true \
            -Dserver.servlet.context-path="${URL_BASE}" \
            -Dserver.host=${LISTEN_IP} \
            -Dserver.port=${LISTEN_PORT} \
            "${RUN_ARRAY[@]}" \
            -jar airsonic.war
